version: '3'

networks:
  inception:
volumes:
  dbdata: {}
  wpdata: {}
# volumes:
#   dbdata:
#     driver: local
#     driver_opts:
#       type: volume
#       o: bind
#       device: 'home/hyospark/data/mariadb'
#   wpdata:
#     driver: local
#     driver_opts:
#       type: volume
#       o: bind
#       device: 'home/hyospark/data/wordpress'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    tty: true

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - wpdata:/var/www/html
    networks:
      - inception
    env_file: .env
    tty: true

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wpdata:/var/www/html
    tty: true
